#!/bin/bash

if zenity --question --text="Do you accept the Privacy Policy, the Readme file and the Licenses files?" --ok-label=Yes --cancel-label=No
then
    # user clicked "Yes"
    break
else
    # user clicked "No"
    echo "Aborting..."
    exit
fi


#Clean
echo "Cleaning..."
sudo apt autoremove

#Donation and quit
if zenity --question --text="The script has finished, would you mind donating? You will get a more compete script (with auto-detection of PPAs and packages.)" --ok-label=Yes --cancel-label=No
then
    # user clicked "Yes"
    zenity --info \ --text="You will now be directed to the developer's donation page. Keep in mind that if you want a more complete script and the ISO in the future, you can always donate again in the future.  Also, note that to receive the download link, you'll have to add in the donation description a valid email, which you can create from scratch for this purpose. Remember to press Ctrl+C and close the terminal when you finish using it. Thank you for your support!"
    xdg-open https://buymeacoffee.com/pietroes
    exit
else
    # user clicked "No"
    zenity --info \ --text="Done."
    exit
fi
